// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
// zfa make PortableSession --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/portable_session/portable_session.dart';
import '../../domain/repositories/portable_session_repository.dart';
import '../datasources/portable_session/portable_session_datasource.dart';

class DataPortableSessionRepository
    with Loggable, FailureHandler
    implements PortableSessionRepository {
  DataPortableSessionRepository(this._dataSource);

  final PortableSessionDataSource _dataSource;

  @override
  Future<PortableSession> get(QueryParams<PortableSession> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<PortableSession>> getList(
    ListQueryParams<PortableSession> params,
  ) {
    return _dataSource.getList(params);
  }

  @override
  Future<PortableSession> create(PortableSession portableSession) {
    return _dataSource.create(portableSession);
  }

  @override
  Future<PortableSession> update(
    UpdateParams<String, PortableSessionPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<void> delete(DeleteParams<String> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
