// Auto-generated by Zorphy
// Generated at: 2026-08-23T17:48:39.517502

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../cookie_entry/cookie_entry.dart';
import '../storage_entry/storage_entry.dart';

part 'portable_session.zorphy.dart';
part 'portable_session.g.dart';

/// PortableSession entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PortableSession {
  String get id;
  String get name;
  String get origin;
  int get createdAt;
  int get updatedAt;
  List<$CookieEntry> get cookies;
  List<$StorageEntry> get storage;
}
