// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
// zfa make PortableSession --methods=get,getList,create,update,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/portable_session/portable_session.dart';

abstract class PortableSessionRepository {
  Future<PortableSession> get(QueryParams<PortableSession> params);
  Future<List<PortableSession>> getList(
    ListQueryParams<PortableSession> params,
  );
  Future<PortableSession> create(PortableSession portableSession);
  Future<PortableSession> update(
    UpdateParams<String, PortableSessionPatch> params,
  );
  Future<void> delete(DeleteParams<String> params);
}

// END GENERATED
