// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
import 'package:zuraffa/zuraffa.dart';

import '../../repositories/portable_session_repository.dart';

class DeletePortableSessionUseCase
    extends CompletableUseCase<DeleteParams<String>> {
  DeletePortableSessionUseCase(this._repository);

  final PortableSessionRepository _repository;

  @override
  Future<void> execute(
    DeleteParams<String> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.delete(params);
  }
}

// END GENERATED
