// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/portable_session/portable_session.dart';
import '../../repositories/portable_session_repository.dart';

class GetPortableSessionUseCase
    extends UseCase<PortableSession, QueryParams<PortableSession>> {
  GetPortableSessionUseCase(this._repository);

  final PortableSessionRepository _repository;

  @override
  Future<PortableSession> execute(
    QueryParams<PortableSession> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
