// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/portable_session/portable_session.dart';
import '../../repositories/portable_session_repository.dart';

class GetPortableSessionListUseCase
    extends UseCase<List<PortableSession>, ListQueryParams<PortableSession>> {
  GetPortableSessionListUseCase(this._repository);

  final PortableSessionRepository _repository;

  @override
  Future<List<PortableSession>> execute(
    ListQueryParams<PortableSession> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}

// END GENERATED
