// GENERATED - DO NOT EDIT
// Generated by zfa for: PortableSession
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/portable_session/portable_session.dart';
import '../../repositories/portable_session_repository.dart';

class UpdatePortableSessionUseCase
    extends
        UseCase<PortableSession, UpdateParams<String, PortableSessionPatch>> {
  UpdatePortableSessionUseCase(this._repository);

  final PortableSessionRepository _repository;

  @override
  Future<PortableSession> execute(
    UpdateParams<String, PortableSessionPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
