// Auto-generated by Zorphy
// Generated at: 2026-08-23T17:48:30.045171

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'storage_entry.zorphy.dart';
part 'storage_entry.g.dart';

/// StorageEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StorageEntry {
  String get key;
  String get value;
  String get area;
  String get origin;
}
