// Auto-generated by Zorphy
// Generated at: 2026-08-23T17:48:09.883042

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'cookie_entry.zorphy.dart';
part 'cookie_entry.g.dart';

/// CookieEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CookieEntry {
  String get name;
  String get value;
  String get domain;
  String get path;
  int? get expiresAt;
  bool get secure;
  bool get httpOnly;
}
